spring:
    application:
        name: ecommerce
    
    datasource:
        url: jdbc:postgresql://localhost:5432/ecommerce
        username: postgres
        password: 4
    
    jpa:
        hibernate:
            ddl-auto: update

        show-sql: true